# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('author', models.CharField(default='', max_length=250, verbose_name='Author name')),
                ('author_id', models.PositiveIntegerField(db_index=True, default=0, null=True, verbose_name='Author id')),
                ('author_email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='Author Email')),
                ('text', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('object_id', models.PositiveIntegerField()),
                ('likes', models.PositiveIntegerField(db_index=True, default=0, null=True, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(db_index=True, default=0, null=True, verbose_name='Dislikes')),
                ('advantages', models.TextField(blank=True, default='', verbose_name='Advantages')),
                ('limitations', models.TextField(blank=True, default='', verbose_name='Limitations')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.Comment', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
