# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta description')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta keywords')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, default='', upload_to=shop.models.make_upload_path, verbose_name='Image')),
                ('count_prod', models.IntegerField(blank=True, null=True)),
                ('reit', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('count_votes', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'verbose_name': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta description')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta keywords')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, default='', upload_to=shop.models.make_upload_path, verbose_name='Image')),
                ('count_prod', models.IntegerField(blank=True, null=True)),
                ('reit', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('count_votes', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='Parent')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('image', models.ImageField(blank=True, default='', upload_to=shop.models.make_upload_path, verbose_name='Image')),
                ('alt', models.CharField(default='', max_length=250, verbose_name='Alt')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'verbose_name': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('published', models.BooleanField(default=True, help_text='Decides whether entity should be treated as active.', verbose_name='Published')),
                ('ordering', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ordering')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta description')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='Meta keywords')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Slug')),
                ('sky', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Sky')),
                ('image', models.ImageField(blank=True, default='', upload_to=shop.models.make_upload_path, verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Price')),
                ('promo', models.BooleanField(default=False, help_text='Show this product on Home page?', verbose_name='Show in home page')),
                ('short_text', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('reit', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('count_votes', models.IntegerField(blank=True, null=True)),
                ('comments_count', models.IntegerField(blank=True, null=True)),
                ('recomend', models.IntegerField()),
                ('saleslider', models.IntegerField()),
                ('price_ue', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('in_shop', models.IntegerField()),
                ('selling_out', models.IntegerField()),
                ('action', models.IntegerField()),
                ('action_time', models.DateTimeField()),
                ('action_name', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='shop.Brand', verbose_name='Category')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='shop.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product', verbose_name='Product'),
        ),
    ]
