# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Ip')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество заходов')),
                ('ban', models.BooleanField(default=0, verbose_name='Исключен')),
                ('g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Google')),
                ('y', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yandex')),
            ],
            options={
                'verbose_name_plural': 'Ip',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.CharField(blank=True, default='', max_length=250, verbose_name='Ip')),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Название')),
                ('ban', models.BooleanField(default=0, verbose_name='Исключен')),
                ('g', models.IntegerField(blank=True, default=0, null=True, verbose_name='Google')),
                ('y', models.IntegerField(blank=True, default=0, null=True, verbose_name='Yandex')),
                ('ip', models.ManyToManyField(blank=True, to='banbyip.Ip')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Ip')),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Ref')),
                ('ref2', models.TextField(blank=True, default='', verbose_name='Ref')),
                ('agent', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Agent')),
                ('host', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Host')),
                ('qu', models.CharField(blank=True, db_index=True, default='', max_length=250, verbose_name='Запрос')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='banbyip.Users', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Visit',
            },
        ),
    ]
